name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: 'Create env file'
      run: |
        touch .env
    #   echo EXAMPLE_ENV_VAR="var_value" >> .env

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-5`" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Docker Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}:${{github.run_number}}_${{ env.SHORT_SHA }}

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.0
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set AKS Credentials
      run: |
        az aks get-credentials --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}
    

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install mc-portfolio-backend ./helm --namespace ${{ secrets.AKS_NAMESPACE }} --set image.repository=ghcr.io/${{ github.repository }},image.tag=${{ github.run_number }}_${{ env.SHORT_SHA }}

    - name: Logout from Azure
      run: az logout        
